$clean_ext = 'acn acr alg aux bbl blg dvi fdb_latexmk fls glg glo gls idx ilg ind lof log lol lot out synctex.gz toc';

# Enable PDF compilation with SyncTeX
$pdf_mode = 1;
$synctex = 1;
$continuous_mode = 1;

# Set the default viewer to Zathura for PDF files
$pdf_previewer = 'start zathura';

# Define a custom command for forward search with Zathura
$pdflatex = 'pdflatex -synctex=1 -interaction=nonstopmode -file-line-error %O %S';

# Open Zathura with the PDF after compilation
$pdf_previewer = "zathura --synctex-forward %l:0:%s %o &";

# Custom dependency and function for nomencl package
add_cus_dep( 'nlo', 'nls', 0, 'makenlo2nls' );
sub makenlo2nls {
	system( "makeindex -s nomencl.ist -o \"$_[0].nls\" \"$_[0].nlo\"" );
}
