#!/bin/sh


# profile file: Runs on login. Environmental variables are set here
#
export PATH="$PATH:$(find $HOME/.local/bin/ -type d -printf ':%p')"

# Default programs:
export EDITOR="vim"
export TERMINAL="st"
export BROWSER="brave"

# XDG stuff
export XDG_CONFIG_HOME="${HOME}"/.config
export XDG_CACHE_HOME="${HOME}"/.cache
export XDG_DATA_HOME="${HOME}"/.local/share
export XDG_STATE_HOME="${HOME}"/.local/state

# Programs that partially support XDG
export __GL_SHADER_DISK_CACHE_PATH="${XDG_CACHE_HOME}"/nv
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME}"/java
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config
export CUDA_CACHE_PATH="${XDG_CACHE_HOME}"/nv
export DVDCSS_CACHE="${XDG_DATA_HOME}"/dvdcss
export GNUPGHOME="${XDG_DATA_HOME}"/gnupg
export HISTFILE="${XDG_STATE_HOME}"/bash/history
export ICEAUTHORITY="${XDG_CACHE_HOME}"/ICEauthority
export IPYTHONDIR="${XDG_CONFIG_HOME}"/ipython
export INPUTRC="${XDG_CONFIG_HOME}"/readline/inputrc
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}"/jupyter
export KDEHOME="${XDG_CONFIG_HOME}"/kde
export KERAS_HOME="${XDG_STATE_HOME}"/keras
export LESSHISTFILE="${XDG_CACHE_HOME}"/less/history
export MYSQL_HISTFILE="${XDG_DATA_HOME}"/mysql_history
export OCTAVE_HISTFILE="${XDG_CACHE_HOME}"/octave/octave_hist
export OCTAVE_SITE_INITFILE="${XDG_CONFIG_HOME}"/octave/octaverc
export PASSWORD_STORE_DIR="${XDG_DATA_HOME}"/pass
export PYTHONPYCACHEPREFIX="${XDG_CACHE_HOME}"/python
export PYTHONSTARTUP="${XDG_CONFIG_HOME}"/python/pythonrc
export PYTHONUSERBASE="${XDG_DATA_HOME}"/python
export TEXMFCONFIG="${XDG_CONFIG_HOME}"/texlive/texmf-config
export TEXMFHOME="${XDG_DATA_HOME}"/texmf
export TEXMFVAR="${XDG_CACHE_HOME}"/texlive/texmf-var
[ -z "$GDMSESSION" ] && export XAUTHORITY="${XDG_RUNTIME_DIR}"/Xauthority
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}"/x11/xinitrc

# For IPOPT
[ -d /usr/local/lib/pkgconfig ] && export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig

[[ -f "${HOME}"/.bashrc ]] && . "${HOME}"/.bashrc

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && [ -z "$GDMSESSION" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

# Switch escape and caps if tty and no passwd required:
# sudo -n loadkeys ${XDG_DATA_HOME:-$HOME/.local/share}/larbs/ttymaps.kmap 2>/dev/null
