#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit, this file will also be sourced.

userresources=${HOME}/.config/x11/xresources
usermodmap=${HOME}/.config/x11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f "$sysresources" ]; then
    xrdb -merge "$sysresources"
fi

if [ -f "$sysmodmap" ]; then
    xmodmap "$sysmodmap"
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ "$GDMSESSION" == "dwm" ]; then
	source ${HOME}/.bash_profile
	{ killall dunst ; setsid -f dunst ;} >/dev/null 2>&1
	setbg &
	remaps &
fi

if [ -z "$GDMSESSION" ]; then
	setbg &			# set the background with the `setbg` script
	#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

	autostart="xcompmgr dunst unclutter remapd"

	for program in $autostart; do
		pidof -sx "$program" || "$program" &
	done >/dev/null 2>&1

	# Ensure that xrdb has finished running before moving on to start the WM/DE.
	[ -n "$xrdbpid" ] && wait "$xrdbpid"
fi
